language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  
before_install:
  - pip install requests
# command to install dependencies
install: 
  - python setup.py install
# command to run tests
script: nosetests MesoPy
